('ITE 003K', 'Introduction to Computer Programming C++', 3, @cost_school_id),
('ITE 004K', 'Introduction to the Internet', 3, @cost_school_id),
('ITE 005K', 'Computer Maintenance and Repairing', 3, @cost_school_id),
('ITE 006K', 'Python Programming', 3, @cost_school_id),
('ITE 007K', 'Java Standard Edition (J2SE)', 3, @cost_school_id),
('ITE 008K', 'Database Concepts', 3, @cost_school_id),
('ITE 009K', 'Java Enterprise Edition (J2EE)', 3, @cost_school_id),
('ITE 010K', 'Multimedia and Graphic Design', 3, @cost_school_id),
('ITE 011K', 'Web Programming Java Script', 3, @cost_school_id),
('ITE 012K', 'Data Communications and Networking', 3, @cost_school_id),
('ITE 013K', 'VBA Programming I', 3, @cost_school_id),
('ITE 014K', 'Creating Animations', 3, @cost_school_id),
('ITE 015K', 'VBA Programming II', 3, @cost_school_id),
('ITE 016K', 'Fundamentals of Computer Networks', 3, @cost_school_id),
('ENG 001K', 'Foundation English I', 3, @cost_school_id),
('ENG 002K', 'Foundation English II', 3, @cost_school_id),
('HIS 101K', 'Cambodian History', 3, @cost_school_id),
('ITE 101K', 'Fundamentals of Computing', 3, @cost_school_id),
('KHM 140K', 'Khmer Culture', 3, @cost_school_id),
('LAW 101K', 'Introduction to Law', 3, @cost_school_id),
('MTH 120K', 'Introduction to Statistics', 3, @cost_school_id),
('POL 101K', 'Introduction to Political Sciences', 3, @cost_school_id),
('PHE 001K', 'Personal Health and Wellness', 3, @cost_school_id),
('COM 101K', 'Interpersonal Communication', 3, @cost_school_id),
('ITE 002K', 'Office Applications', 3, @cost_school_id),
('BUS 005K', 'Foundations of Teamwork and Leadership', 3, @cost_school_id),
('ITE 102', 'Introduction to Computer Programming C++', 3, @cost_school_id),
('ITE 103', 'Introduction to the Internet', 3, @cost_school_id),
('ITE 105', 'Computer Architecture', 3, @cost_school_id),
('ITE 106', 'Computer Maintenance and Repairing', 3, @cost_school_id),
('ITE 201', 'Python Programming', 3, @cost_school_id),
('ITE 202', 'Java Standard Edition (J2SE)', 3, @cost_school_id),
('ITE 203', 'Database Concepts', 3, @cost_school_id),
('ITE 204', 'Java Enterprise Edition (J2EE)', 3, @cost_school_id),
('ITE 205', 'Multimedia and Graphic Design', 3, @cost_school_id),
('ITE 207', 'Data Communications and Networking', 3, @cost_school_id),
('ITE 208', 'UI/UX Design', 3, @cost_school_id),
('ITE 209', 'Dart Programming', 3, @cost_school_id),
('ITE 210', 'Digital Media Technology', 3, @cost_school_id),
('ITE 301', 'Database Administration and Management', 3, @cost_school_id),
('ITE 302', 'Cisco Networking I', 3, @cost_school_id),
('ITE 303', 'Web Programming PHP and MySQL', 3, @cost_school_id),
('ITE 304', 'Android App Development', 3, @cost_school_id),
('ITE 305', 'System Analysis and Design', 3, @cost_school_id),
('ITE 306', 'Cisco Networking II', 3, @cost_school_id),
('ITE 307', 'Software Project Management', 3, @cost_school_id),
('ITE 308', 'DevOps Engineering', 3, @cost_school_id),
('ITE 310', 'AI/ML Technology', 3, @cost_school_id),
('ITE 311', 'Flutter App Development', 3, @cost_school_id),
('ITE 401', 'Dynamic Web Design', 3, @cost_school_id),
('ITE 403', 'E-Commerce Technology', 3, @cost_school_id),
('ITE 404', 'Data Warehousing and Data Mining', 3, @cost_school_id),
('ITE 405', 'Windows System Administration', 3, @cost_school_id),
('ITE 406', 'Linux/Unix System Administration', 3, @cost_school_id),
('ITE 407', 'Routing and Switching', 3, @cost_school_id),
('ITE 408', 'Cyber Security', 3, @cost_school_id),
('COM 101', 'Interpersonal Communication', 3, @cost_school_id),
('ENG 101', 'College English', 3, @cost_school_id),
('ENG 102', 'English Composition', 3, @cost_school_id),
('HIS 101', 'Cambodian History', 3, @cost_school_id),
('INT 104', 'Geopolitics and Globalisation', 3, @cost_school_id),
('ITE 101', 'Fundamentals of Computing', 3, @cost_school_id),
('KHM 140', 'Khmer Culture', 3, @cost_school_id),
('LAW 101', 'Introduction to Law', 3, @cost_school_id),
('MTH 120', 'Introduction to Statistics', 3, @cost_school_id),
('PHL 104', 'Critical Reasoning', 3, @cost_school_id),
('PHL 105', 'Moral Philosophy', 3, @cost_school_id),
('POL 101', 'Introduction to Political Science', 3, @cost_school_id),
('PSY 101', 'Introduction to Psychology', 3, @cost_school_id),
('RES 201', 'Introduction to Research', 3, @cost_school_id),
('RES 301', 'Research Methodology', 3, @cost_school_id),
('WMN 201', 'Perspectives on Women in Society', 3, @cost_school_id),
('BUS 304', 'Leadership Skills', 3, @cost_school_id),
('ENG 107', 'The Written Language', 3, @cost_school_id),
('ENG 122', 'Further English for Non-Majors', 3, @cost_school_id),
('ENG 219', 'Business Communication', 3, @cost_school_id),
('ORG 201', 'Organizational Behavior', 3, @cost_school_id),
('ETC 201', 'Introduction to Telecommunications', 3, @cost_school_id),
('ETC 301', 'Electronics Theory', 3, @cost_school_id),
('ETC 302', 'Huawei HCIA I', 3, @cost_school_id),
('ETC 303', 'Electronic Circuit Design', 3, @cost_school_id),
('ETC 304', 'Digital Logic Design', 3, @cost_school_id),
('ETC 305', 'Antenna Theory and Design', 3, @cost_school_id),
('ETC 306', 'Huawei HCIA II', 3, @cost_school_id),
('ETC 401', 'Microwave Engineering', 3, @cost_school_id),
('ETC 402', 'Mobile and Wireless Communication Systems', 3, @cost_school_id),
('ETC 403', 'Optical Fiber Systems and Networks', 3, @cost_school_id),
('ETC 404', 'Telecommunications and Network Security', 3, @cost_school_id),
('ETC 405', 'Satellite Communications', 3, @cost_school_id),
('ITE 309', 'iOS App Development', 3, @cost_school_id),
('ITE 402', 'Spring Framework', 3, @cost_school_id),
('ITE 409', '.NET Programming', 3, @cost_school_id),
('ITE 410', 'OOP Programming', 3, @cost_school_id),
('ITE 411', 'Professional Database (Oracle)', 3, @cost_school_id),
('ITE 412', 'Blockchain and FinTech Technology', 3, @cost_school_id),
